server:
  port: 8080
  # tomcat:
  #   connection-timeout: 20s
jwt:
  secretKey : "mysupersecretkeymysupersecretkeymysupersecretkeymysupersecretkey1234"
  expiration_time: 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: tuanduog
    password: abc123!@#
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework.web: ERROR
    com.example: DEBUG

